import profilepic  from  './img/profile.jpg';

export const post = [
    {
      id: 1,
      userId : 'mr.kareliya_456',
      userName: "Harshil Kareliya",
      title: "amazing city",
      profileImg : profilepic,
      postImage : 'https://www.spec-india.com/wp-content/uploads/2020/06/Full_Stack.png',
      description: "City is everything that provide everything that we need, city is over first monterh 77",
      like: 103,
      comment: 0,
      share: 80,
    },
    {
      id: 1,
      userId : 'mr.kareliya_456',
      userName: "Harshil Kareliya",
      title: "amazing city",
      profileImg : profilepic,
      postImage : 'https://th.bing.com/th/id/OIP.CEJZdk7LfdT0LWq3KwIjAwHaE7?rs=1&pid=ImgDetMain',
      description: "City is everything that provide everything that we need, city is over first monterh 77",
      like: 103,
      comment: 4.2,
      share: 8.1,
    },
    {
      id: 1,
      userId : 'mr.kareliya_456',
      userName: "Harshil Kareliya",
      title: "amazing city",
      profileImg : profilepic,
      postImage : 'https://th.bing.com/th/id/OIP.JFxjtt1mC1Gn7wSZ_RwqZQHaNK?w=728&h=1294&rs=1&pid=ImgDetMain',
      description: "City is everything that provide everything that we need, city is over first monterh 77",
      like: 103,
      comment: 4.2,
      share: 8.1,
    },
];
